import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { SUBJECTS } from '../constants';
import { getSubjectFRQCount } from '../services/firestoreService';
import { SubjectInfo, SubjectSlug } from '../types';

type CountState = Record<SubjectSlug, number | null>;

const initialCounts: CountState = SUBJECTS.reduce((acc, subject) => {
  acc[subject.slug] = null;
  return acc;
}, {} as CountState);

const SubjectCard: React.FC<{ subject: SubjectInfo; count: number | null }> = ({
  subject,
  count,
}) => {
  const isLoading = count === null;
  const isDisabled = !isLoading && count === 0;

  const content = (
    <div
      className={`relative h-full rounded-2xl border-2 bg-white p-6 shadow-sm transition-all duration-200 ${
        isDisabled
          ? 'opacity-60 cursor-not-allowed border-gray-200'
          : `hover:shadow-md hover:-translate-y-0.5 border-gray-200 hover:${subject.accentClass.split(' ')[0]}`
      }`}
    >
      <div className={`inline-block px-3 py-1 rounded-full text-xs font-semibold text-white ${subject.colorClass}`}>
        {subject.shortName}
      </div>
      <h2 className="mt-4 text-xl font-semibold text-gray-900">{subject.displayName}</h2>
      <p className="mt-2 text-sm text-gray-500">
        {isLoading
          ? 'Loading count…'
          : isDisabled
          ? 'No archived FRQs yet'
          : `${count.toLocaleString()} FRQ${count === 1 ? '' : 's'} available`}
      </p>
      {!isDisabled && !isLoading && (
        <div className={`mt-6 text-sm font-medium ${subject.accentClass.split(' ').slice(1).join(' ')}`}>
          Browse archive →
        </div>
      )}
      {isDisabled && (
        <div className="mt-6 text-sm font-medium text-gray-400">Coming soon</div>
      )}
    </div>
  );

  if (isDisabled || isLoading) {
    return <div aria-disabled={isDisabled}>{content}</div>;
  }

  return (
    <Link
      to={`/subject/${subject.slug}`}
      className="block focus:outline-none focus:ring-2 focus:ring-indigo-500 rounded-2xl"
    >
      {content}
    </Link>
  );
};

const SubjectPicker: React.FC = () => {
  const [counts, setCounts] = useState<CountState>(initialCounts);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      // Fire all subject count queries in parallel — each is a cheap
      // aggregate count, and the UI can progressively render as results
      // come in.
      const results = await Promise.all(
        SUBJECTS.map(async (subject) => {
          const count = await getSubjectFRQCount(subject.slug);
          return [subject.slug, count] as const;
        })
      );

      if (cancelled) return;
      setCounts((prev) => {
        const next = { ...prev };
        for (const [slug, count] of results) {
          next[slug] = count;
        }
        return next;
      });
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-12 sm:py-20">
      <div className="text-center mb-12">
        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900">AP FRQ Archive</h1>
        <p className="mt-3 text-base sm:text-lg text-gray-600 max-w-2xl mx-auto">
          Browse and download every AP Free Response Question generated by the AP Infinite
          FRQ Generators. Pick a subject to get started.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {SUBJECTS.map((subject) => (
          <SubjectCard key={subject.slug} subject={subject} count={counts[subject.slug]} />
        ))}
      </div>
    </div>
  );
};

export default SubjectPicker;
